- hosts: bigips
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: 192.168.86.49
    ansible_user: admin
    ansible_httpapi_password: totallynotarealpassword
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Start declaration
      bigip_as3_deploy:
        content: "{{ lookup('file', 'awsgatewaydeclare.json') }}"
