- hosts: all
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: "192.168.86.40"
    ansible_user: "admin"
    ansible_httpapi_password: "totallyarealpassword"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Ensure an existing image is activated in specified volume
      bigip_software_install:
        image: BIGIP-16.1.3.2-0.0.4.iso
        volume: HD1.3
      register: task
