- hosts: all
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: "192.168.86.40"
    ansible_user: "admin"
    ansible_httpapi_password: "YAYeff52022!"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Run multiple commands on remote nodes
      bigip_command:
        commands:
          - run util bash -c "cp /config/user_alert.conf /config/user_alert.conf.bak"	
          - run util bash -c "curl https://raw.githubusercontent.com/npmaslow/irules/main/user_alert.conf > /config/user_alert.conf"
